demo: remove deprecated ansible_ssh_host
rmohr/ceph-cinder-demo pull request #17
Opened 2018-02-21 16:54 UTC by karmab

Signed-off-by: karimb <karimboumedhel@gmail.com>

2018-02-22 15:54 UTC, aglitke approved these changes

2018-02-22 16:02 UTC, rmohr reviewed
@karmab does it matter if we use ansible_ssh_host in an inventory? WIll ansible_host still be filled?

2018-02-26 15:15 UTC, aglitke requested changes
Actually we should not merge this.  The openshift-ansible repo expects the deprecated form.  When it is missing I get errors when executing the playbooks.

2018-02-27 09:00 UTC, rmohr commented
@aglitke this only changes the variables used for our "external" vagrant run. Could you check if having it would work for you? I am now on a never ansible 2 version which completely removed ansible_ssh_host. However openshift still installs fine inside the vms.

2019-10-10 16:13 UTC, closed without merging